<a href="https://colab.research.google.com/github/DT1768/ML-DS-Lab-MSU-PGDCA-Sem-2/blob/main/LAB-6/Lab_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Name: Dhruvkumar Dhirubhai Thakkar** 

**Assignment-6**	

**PRN: 8021028675**

**Machine Learning and Data Science Lab**


# **Karl Pearson Coefficient of correlation**

**Q1: Find the value of correlation co-efficient from the following data.**

Age = [43,21,25,42,57,59]

Glucose = [99,65,79,75,87,81]

In [26]:
import numpy as np
import math

x = [43,21,25,42,57,59]
y = [99,65,79,75,87,81]

r =(sum((x - np.mean(x))*(y-np.mean(y))))/(math.sqrt(sum((x - np.mean(x))*(x - np.mean(x))))*math.sqrt(sum((y - np.mean(y))*(y - np.mean(y)))))
print("Co-efficient of correlation between age and glucose level is: ",r)
if(r>0):
  print("Positive Correlation")
elif (r<0):
  print("Negative Correlation")
else:
  print("Zero Correlation")

Co-efficient of correlation between age and glucose level is:  0.5298089018901744
Positive Correlation


**Q2: Find the value of correlation co-efficient from the following data.**

years of education = [10,12,15,8]

Age of entry in labour force = [16,17,18,15]

In [27]:
import numpy as np
import math

x = [10,12,15,8]
y = [16,17,18,15]

r =(sum((x - np.mean(x))*(y-np.mean(y))))/(math.sqrt(sum((x - np.mean(x))*(x - np.mean(x))))*math.sqrt(sum((y - np.mean(y))*(y - np.mean(y)))))
print("Co-efficient of correlation between years of education and age of entry in labour force is: ",r)
if(r>0):
  print("Positive Correlation")
elif (r<0):
  print("Negative Correlation")
else:
  print("Zero Correlation")

Co-efficient of correlation between years of education and age of entry in labour force is:  0.9943767126843688
Positive Correlation


**Q3: Find the value of correlation co-efficient from the following data.**

Percentage of students having free meals = [14.4,7.2,27.5,33.8,38,15.9,4.9]

percentage of students scoring above 8.5 CGPA= [54,64,44,32,37,68,62]

In [28]:
import numpy as np
import math

x = [14.4,7.2,27.5,33.8,38,15.9,4.9]
y = [54,64,44,32,37,68,62]

r =(sum((x - np.mean(x))*(y-np.mean(y))))/(math.sqrt(sum((x - np.mean(x))*(x - np.mean(x))))*math.sqrt(sum((y - np.mean(y))*(y - np.mean(y)))))
print("Co-efficient of correlation between Percentage of students having free meals and percentage of students scoring above 8.5 CGPA: ",r)
if(r>0):
  print("Positive Correlation")
elif (r<0):
  print("Negative Correlation")
else:
  print("Zero Correlation")

Co-efficient of correlation between Percentage of students having free meals and percentage of students scoring above 8.5 CGPA:  -0.899211634084388
Negative Correlation


**Q4: Find the value of correlation co-efficient from the following data.**

Statistics = [1,3,3,4,5,6,7,8,9,10]

Mathematics = [2,4,1,5,3,9,7,10,6,8]

In [29]:
import numpy as np
import math

x = [1,3,3,4,5,6,7,8,9,10]
y = [2,4,1,5,3,9,7,10,6,8]

r =(sum((x - np.mean(x))*(y-np.mean(y))))/(math.sqrt(sum((x - np.mean(x))*(x - np.mean(x))))*math.sqrt(sum((y - np.mean(y))*(y - np.mean(y)))))
print("Co-efficient of correlation between Statistics and Mathematics is: ",r)
if(r>0):
  print("Positive Correlation")
elif (r<0):
  print("Negative Correlation")
else:
  print("Zero Correlation")

Co-efficient of correlation between Statistics and Mathematics is:  0.7683448443100817
Positive Correlation


**Q5: Find the value of correlation co-efficient from the following data.**

x = [43,96,74,38,35,43,22,56,35,80]

y = [30,94,84,13,30,18,30,41,48,45]

In [30]:
import numpy as np
import math

x = [43,96,74,38,35,43,22,56,35,80]
y = [30,94,84,13,30,18,30,41,48,45]

r =(sum((x - np.mean(x))*(y-np.mean(y))))/(math.sqrt(sum((x - np.mean(x))*(x - np.mean(x))))*math.sqrt(sum((y - np.mean(y))*(y - np.mean(y)))))
print("Co-efficient of correlation between x and y is: ",r)
if(r>0):
  print("Positive Correlation")
elif (r<0):
  print("Negative Correlation")
else:
  print("Zero Correlation")

Co-efficient of correlation between x and y is:  0.7911774518253507
Positive Correlation


# **Cross-Validation to evaluate machine learning model**

**1) Hold-out Method**

In [31]:
from sklearn.model_selection import train_test_split
X = [10,20,30,40,50,60,70,80,90,100]
train, test= train_test_split(X,test_size=0.4, random_state=1)
print("Train:",train,"Test:" ,test)

Train: [10, 40, 20, 80, 90, 60] Test: [30, 100, 70, 50]


**2) Leave One Out Cross-Validation**

In [32]:
from sklearn.model_selection import LeaveOneOut
X = [10,20,30,40,50,60,70,80,90,100]

l = LeaveOneOut()

for train, test in l.split(X):

    print("%s %s"% (train,test))


[1 2 3 4 5 6 7 8 9] [0]
[0 2 3 4 5 6 7 8 9] [1]
[0 1 3 4 5 6 7 8 9] [2]
[0 1 2 4 5 6 7 8 9] [3]
[0 1 2 3 5 6 7 8 9] [4]
[0 1 2 3 4 6 7 8 9] [5]
[0 1 2 3 4 5 7 8 9] [6]
[0 1 2 3 4 5 6 8 9] [7]
[0 1 2 3 4 5 6 7 9] [8]
[0 1 2 3 4 5 6 7 8] [9]


**3) K-Fold Cross-Validation**

In [33]:
from sklearn.model_selection import KFold
X = ["a",'b','c','d','e','f']

kf = KFold(n_splits=4, shuffle=False, random_state=None)

for train, test in kf.split(X):
    print("Train data",train,"Test data",test)

Train data [2 3 4 5] Test data [0 1]
Train data [0 1 4 5] Test data [2 3]
Train data [0 1 2 3 5] Test data [4]
Train data [0 1 2 3 4] Test data [5]


**4) Stratified K-Fold Cross-Validation**

In [34]:
from sklearn.model_selection import StratifiedKFold
X = np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
y= np.array([0,0,1,0,1,1])

skf = StratifiedKFold(n_splits=3,random_state=None,shuffle=False)

for train_index,test_index in skf.split(X,y):
    print("Train:",train_index,'Test:',test_index)
    X_train,X_test = X[train_index], X[test_index]
    y_train,y_test = y[train_index], y[test_index]


Train: [1 3 4 5] Test: [0 2]
Train: [0 2 3 5] Test: [1 4]
Train: [0 1 2 4] Test: [3 5]
